apiVersion: v1
kind: Service
metadata:
  name: e-commerce-users
  labels:
    app: e-commerce-users
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: e-commerce-users