apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-reverseproxy
  labels:
    app: e-commerce-reverseproxy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-reverseproxy
  template:
    metadata:
      labels:
        app: e-commerce-reverseproxy
    spec:
      containers:
      - image: abdallahelshamy/e-commerce-reverseproxy
        name: e-commerce-reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always

         