apiVersion: v1
kind: Service
metadata:
  name: e-commerce-orders
  labels:
    app: e-commerce-orders
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: e-commerce-orders